#!/bin/sh -efu


dpi=200

for i in "$@"; do
  base=${i%.*}
  echo "$base"

  #$BRD_DIR/*.gpx --trk_draw_transp 0.5 --trk_draw_dots 0 --trk_draw_width 3\
  #--cmap_load "$CMAP"
  # --map $base.map

  ms2render "vmap/$base.vmap2" "vmap_base/${base}_b.vmap2" --out "$base.png"\
      --config render.cfg -t "" --define "{\"nom_name\":\"$base\"}"\
      --mkref nom_fi --name "$base" --dpi "$dpi" --margins 10 --top_margin 30\
      --title "$base" --title_size 20\
      --png_format pal
done
