MOD_SOURCES := lib.cpp
MOD_HEADERS := lib.h
PROGRAMS :=\
  map_brd find_object\
  import_fi1 import_fi2 import_no\
  make_map update_map\
test

MODDIR := /home/sla/mapsoft2/modules
include $(MODDIR)/Makefile.inc
