#!/bin/sh -eu

# Update text and point objects from ../vmap_base/*_t.vmap2

files=${@}

for f in $files; do
  base=${f%%.*}
  ../progs/update_map --apply --types ../types.cfg --map ${base} --patch_file oconvs.txt\
     "../vmap_base/${base}_t.vmap2.gz" "${base}.vmap2"
done