#!/bin/sh -eu

# Update text and point objects from ../vmap_base/*_t.vmap2

files=${@:-*.vmap2}

for f in $files; do
  base=${f%.vmap2}
  [ -f "$f" ] || cp ../vmap_base/${base}_t.vmap2 ${base}.vmap2

  ../progs/update_text --types ../types.cfg "../vmap_base/${base}_t.vmap2" "${base}.vmap2"
done