#!/bin/sh -eu

# Update text and point objects from ../vmap_base/*_t.vmap2

files=${@}

for f in $files; do
  base=${f%%.*}
  ../progs/update_map --types ../types.cfg --patch_file ${base}.cnv\
     "../vmap2/${base}_t.vmap2.gz" "${base}.vmap2"
done